name: npm audit

on:
  push:
    branches: [ audit ]
  pull_request:
    branches: [ audit ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Python Package
      run: |
        pip install npm --upgrade npm
        npm update
        npm audit fix --force
