name: 'npm root install'

on: [pull_request, push]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          versionsAsRoot: true
          type: majors
          preset: '>=10'

  nodes:
    needs: [matrix]
    permissions:
      contents: read
    name: 'nvm install-latest-npm'
    runs-on: ubuntu-latest


  node:
    permissions:
      contents: none
    name: 'nvm install-latest-npm'
    needs: [nodes]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
